version: '3.4'

services:
  vocative:
    build: .
    ports:
     - "8090:8080"
    environment:
      VOCATIVE_LISTEN_IP: 0.0.0.0
      VOCATIVE_LISTEN_PORT: 8080
      VOCATIVE_DB_HOSTNAME: postgresql
      VOCATIVE_DB_PORT: 5432
      VOCATIVE_DB_USER: postgres
      VOCATIVE_DB_PASSWORD: password
      VOCATIVE_DB_NAME: vocative
      VOCATIVE_DB_RETRIES: 100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healtz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes: 
      - ./vocative-api:/vocative-api
    depends_on:
      - postgresql
  postgresql:
    image: mdillon/postgis:11
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vocative
    volumes: 
      - ./db:/var/lib/postgresql/data
      - ./data:/data
